project:
  type: website
  output-dir: docs

website:
  title: "week9 weekly"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
 <iframe src="docs/GLL.Resume.pdf" width="100%" height="600px"></iframe>

        

format:
  html:
    theme: quartz
    mainfont: arial
    fontsize: 1.25rem
    fontcolor: "#FCFCFC"
    linkcolor: "#9D9D9D"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

